### ISSUE TITLE
Cannot submit TOSCA in MiCADOv5 on OpenStack

### ISSUE THREAD

**Issue by jaydesl** [micado-scale/ansible-micado#53]
### Description
TOSCAParser fails (hangs trying to pull the custom types file *micado_types.yaml* from GitHub)

### Cause
An MTU mismatch between Docker (default 1500) and OpenStack (default 1450) causes HTTPS requests from inside a container to hang.

### Steps to Reproduce
Deploy MiCADOv5 master to an OpenStack instance and submit a TOSCA template

### Related Links
https://github.com/moby/moby/issues/20178#issuecomment-228531711
https://rahulait.wordpress.com/2016/02/28/modifying-default-mtu-for-docker-containers/

### Versions
0.5.x

**Comment by jaydesl** [comment]
See **Related Links** for the workaround

**Comment by fsattila** [comment]
I've extended the #55 solution in the #65 and #71 PRs. I've set the default interface's MTU instead of a fixed value. I've also set this value in worker docker daemon configuration and in the master and worker component's compose file, too. Related issue: https://github.com/moby/moby/issues/34981

The docker adaptor in the Tosca submitter has to be extended to set the MTU value in the deployed application's compose file like in the component's compose file (9508371dd895a2fd96aa24ca78362fd0e97d243c). The MTU value of the default network interface can be reached in several ways.
